# Taogelog-pages configuration

name: 涛声依旧
description: Welcome to Taogeblog！

# url is currently only used only for the RSS feed in feed.xml
url: https://astronger.github.io/taogeblog-pages/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/taogeblog-pages'
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language  中:cn  英：en
lan: "cn" 

paginate: 10

highlighter: rouge
markdown: astronger
gems: ['Taogeblog-pages']

exclude: ['README.md', 'LICENSE', "*.bak"]
